<?php

namespace App\Presenters;

use App\Forms;
use Nette\Application\UI\Form;


class SignPresenter extends BasePresenter
{
	/** @var Forms\SignInFormFactory */
	private $signInFactory;

	/** @var Forms\SignUpFormFactory */
	private $signUpFactory;


	public function __construct(Forms\SignInFormFactory $signInFactory, Forms\SignUpFormFactory $signUpFactory)
	{
		$this->signInFactory = $signInFactory;
		$this->signUpFactory = $signUpFactory;
	}

    protected function beforeRender()
    {
        $this->setLayout('admin');
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }


    /**
	 * Sign-in form factory.
	 * @return Form
	 */
	protected function createComponentSignInForm()
	{
		return $this->signInFactory->create(function () {
			$this->redirect('Admin:');
		});
	}


    public function actionUp()
    {
        $this->flashMessage('Cannot sign up.');
        $this->redirect('in');
    }


	public function actionOut()
	{
		$this->getUser()->logout();
        $this->redirect('Homepage:');
	}
}
